import { anakin, darthVader, luke, mestreYoda, obiwan, padme, palpatine, maceWindu, quiGon } from "../assets";

export const quotes = [
  { text: "A Força é forte em minha família.", author: "Luke Skywalker", image: luke, color: "#10B981" },
  { text: "Você subestima o poder do lado sombrio.", author: "Darth Vader", image: darthVader, color: "#EF4444" },
  { text: "Você era meu irmão, Anakin. Eu te amava.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Faça ou não faça. Tentativa não há!", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "Você está no Conselho, mas não é um Mestre.", author: "Mace Windu", image: maceWindu, color: "#8B5CF6" },
  { text: "Me derrube e me tornarei mais poderoso do que imagina.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Não posso aprovar um curso que leve à guerra.", author: "Padmé Amidala", image: padme, color: "#964B00" },
  { text: "Bem-vindo, jovem Skywalker.", author: "Palpatine", image: palpatine, color: "#EF4444" },
  { text: "Sou um Jedi, como meu pai antes de mim.", author: "Luke Skywalker", image: luke, color: "#10B981" },
  { text: "Passe adiante o que aprendeu.", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "O lado negro é mais fácil, mais sedutor.", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "Eu trouxe paz, liberdade, justiça e segurança ao meu novo império!", author: "Anakin Skywalker", image: anakin, color: "#3B82F6" },
  { text: "Se você me matar, eu me tornarei mais poderoso do que pode imaginar.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "O fracasso é o maior dos mestres.", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "Se o chanceler não desistir de seus poderes de emergência, teremos que tomar medidas.", author: "Mace Windu", image: maceWindu, color: "#8B5CF6" },
  { text: "Esses não são os droides que você procura.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Tamanho não importa.", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "O medo é o caminho para o lado negro.", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "A Força estará com você. Sempre.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Seu foco determina sua realidade.", author: "Qui‑Gon Jinn", image: quiGon, color: "#10B981" },
  { text: "Você era o escolhido!", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Sua confiança no Senador Amidala é ingênua.", author: "Palpatine", image: palpatine, color: "#EF4444" },
  { text: "Concentre-se aqui e agora.", author: "Qui‑Gon Jinn", image: quiGon, color: "#10B981" },
  { text: "Sempre há um peixe maior.", author: "Qui‑Gon Jinn", image: quiGon, color: "#10B981" },
  { text: "Crepúsculo está sobre mim… Esse é o caminho da Força.", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "A Força é poderosa neste aqui.", author: "Darth Vader", image: darthVader, color: "#EF4444" },
  { text: "Em minha experiência, sorte não existe.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Eu tenho um mau pressentimento sobre isso.", author: "Vários", image: obiwan, color: "#3B82F6" },
  { text: "A capacidade de falar não faz você inteligente.", author: "Qui‑Gon Jinn", image: quiGon, color: "#10B981" },
  { text: "Que a Força esteja com você.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" }
];
