import { anakin, darthVader, luke, mestreYoda, obiwan, padme, palpatine, maceWindu, quiGon } from "../assets";

export const quotes = [
  { text: "A Força é forte em minha família.", author: "Luke Skywalker", image: luke, color: "#10B981" },
  { text: "Você subestima o poder do lado sombrio.", author: "Darth Vader", image: darthVader, color: "#EF4444" },
  { text: "Você era meu irmão, Anakin. Eu te amava.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Faça ou não faça. Tentativa não há!", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "Me derrube e me tornarei mais poderoso do que imagina.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Você está no Conselho, mas não é um Mestre.", author: "Mace Windu", image: maceWindu, color: "#8B5CF6" },
  { text: "Não posso aprovar um curso que leve à guerra.", author: "Padmé Amidala", image: padme, color: "#964B00" },
  { text: "Bem-vindo, jovem Skywalker.", author: "Palpatine", image: palpatine, color: "#EF4444" },
  { text: "Sou um Jedi, como meu pai antes de mim.", author: "Luke Skywalker", image: luke, color: "#10B981" },
  { text: "Passe adiante o que aprendeu.", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "O lado negro é mais fácil, mais sedutor.", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "Serei o Jedi mais poderoso de todos os tempos.", author: "Anakin Skywalker", image: anakin, color: "#3B82F6" },
  { text: "Sua fé te guia, jovem Padawan.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Mesmo na derrota, há uma lição.", author: "Luke Skywalker", image: luke, color: "#10B981" },
  { text: "Se o chanceler não desistir de seus poderes de emergência, teremos que tomar medidas.", author: "Mace Windu", image: maceWindu, color: "#8B5CF6" },
  { text: "Esses não são os droides que você procura.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Tamanho não importa.", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "Perdão traz libertação.", author: "Padmé Amidala", image: padme, color: "#964B00" },
  { text: "A Força estará com você. Sempre.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "O medo é o caminho para o lado negro.", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "Tudo que eu faço, é para garantir a paz, produtividade e progresso.", author: "Palpatine", image: palpatine, color: "#EF4444" },
  { text: "Você subestima o poder de uma mente calma.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Você está no Conselho, mas não é um Mestre.", author: "Mace Windu", image: maceWindu, color: "#8B5CF6" },
  { text: "A Força circula entre todos nós.", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "A redenção começa com um passo.", author: "Luke Skywalker", image: luke, color: "#10B981" },
  { text: "Seu foco determina sua realidade.", author: "Qui‑Gon Jinn", image: quiGon, color: "#10B981" },
  { text: "Minha esperança é maior que minha dor.", author: "Anakin Skywalker", image: anakin, color: "#3B82F6" },
  { text: "A situação está se tornando perigosa. Precisamos agir com sabedoria.", author: "Mace Windu", image: maceWindu, color: "#8B5CF6" },
  { text: "Somos a centelha que acenderá a República.", author: "Padmé Amidala", image: padme, color: "#964B00" },
  { text: "Há sempre luz, mesmo na mais profunda escuridão.", author: "Anakin Skywalker", image: anakin, color: "#3B82F6" },
  { text: "Ninguém está realmente perdido para sempre.", author: "Luke Skywalker", image: luke, color: "#10B981" },
  { text: "O lado sombrio da Força cerca o chanceler.", author: "Mace Windu", image: maceWindu, color: "#8B5CF6" },
  { text: "Você era o escolhido!", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Sua confiança no Senador Amidala é ingênua.", author: "Palpatine", image: palpatine, color: "#EF4444" },
  { text: "Nosso destino está próximo, criação nossa.", author: "Padmé Amidala", image: padme, color: "#964B00" },
  { text: "Faça o que eu mandar, e encontrará seu lugar à direita de mim.", author: "Palpatine", image: palpatine, color: "#EF4444" },
  { text: "Concentre-se aqui e agora.", author: "Qui‑Gon Jinn", image: quiGon, color: "#10B981" },
  { text: "Treine sua mente. Solte o medo de perder.", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "Não", author: "Darth Vader", image: darthVader, color: "#EF4444" },
  { text: "Sinto sua falta de fé.", author: "Darth Vader", image: darthVader, color: "#EF4444" },
  { text: "Somos guardiões da galáxia.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Sempre há um peixe maior.", author: "Qui‑Gon Jinn", image: quiGon, color: "#10B981" },
  { text: "Crepúsculo está sobre mim… Esse é o caminho da Força.", author: "Yoda", image: mestreYoda, color: "#10B981" },
  { text: "Trouxe paz, liberdade, justiça e segurança ao meu império.", author: "Anakin Skywalker", image: anakin, color: "#3B82F6" },
  { text: "Nós somos a centelha que reacenderá a República.", author: "Padmé Amidala", image: padme, color: "#964B00" },
  { text: "A Força é poderosa neste aqui.", author: "Darth Vader", image: darthVader, color: "#EF4444" },
  { text: "A Força estará com você. Sempre.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Em minha experiência, sorte não existe.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" },
  { text: "Aconteça o que acontecer, o próximo passo deve ser um caminho mais brilhante.", author: "Palpatine", image: palpatine, color: "#EF4444" },
  { text: "Eu tenho um mau pressentimento sobre isso.", author: "Vários", image: obiwan, color: "#3B82F6" },
  { text: "Quando souber por que não está pronto, estará.", author: "Qui‑Gon Jinn", image: quiGon, color: "#10B981" },
  { text: "A capacidade de falar não faz você inteligente.", author: "Qui‑Gon Jinn", image: quiGon, color: "#10B981" },
  { text: "Não vou deixá-lo aqui. Irei para Alderaan com você.", author: "Luke Skywalker", image: luke, color: "#10B981" },
  { text: "Que a Força esteja com você.", author: "Obi‑Wan Kenobi", image: obiwan, color: "#3B82F6" }
]
